// AUTO-GENERATED by Agent_Max/tools/schema/jsonschema_to_ts.py — do not edit by hand.
// Source: Agent_Max/api/models/feature_flags.py (Pydantic v2 JSON Schema)

export interface FeatureFlagsRolloutInfo {
  websocket_enabled: boolean;
  evidence_validation_enabled: boolean;
  billing_enabled: boolean;
  hmac_enabled: boolean;
}

export interface FeatureFlagsResponse {
  flags: Record<string, boolean>;
  user_id?: null | string;
  rollout_info: FeatureFlagsRolloutInfo;
}
